### ISSUE TITLE
Ability to selectively disable / enable in IDE

### ISSUE THREAD

**Issue by turadg** [hosseinmd/prettier-plugin-jsdoc#157]
I'm trying to adopt this in a monorepo one package at a time. The [docs say](https://github.com/hosseinmd/prettier-plugin-jsdoc#config) that to "ignore some type of files remove "prettier-plugin-jsdoc" from plugins or add empty plugins".

I've tried both and Prettier's autoloader still enables it. For example, with this minimal config it still runs this jsdoc plugin,
```
  {
    "plugins": []
  }
```

I wonder if that advice was for an older version of Prettier. Can anyone confirm these instructions in the README work for them?

In Prettier 2.6 plugins will be autoloaded, which can be disabled, but once they're loaded it's not clear to me that Prettier supports _disabling_ them. For the IDE case I need the plugin to be loaded so the paths that use it can be formatted and there's no way to "unload" it for the other paths.

**Comment by hosseinmd** [comment]
This seems to be a prettier bug. However, for solving this, you can add on documented option `jsdocParser:false` to prettier config

**Comment by hosseinmd** [comment]
> This seems to be a prettier bug. However, for solving this, you can add not documented option `jsdocParser:false` to prettier config

**Comment by turadg** [comment]
> you can add on documented option `jsdocParser:false`

That'd be great! However it doesn't appear to be working (at least with Prettier 2.6.0).

With this `testfile.js`:
```
/**
 * For example, if the stored keys are:
 * bar
 * baz
 * foocount
 * foopriority
 * joober
 * plugh.3
 * plugh.47
 * plugh.8
 * zot
 */
```

This config:
```
{
  "plugins": ["prettier-plugin-jsdoc"],
  "jsdocParser": false
}
```
Yields for `prettier testfile.js`
```
[warn] Ignored unknown option { jsdocParser: false }.
/**
 * For example, if the stored keys are: bar baz foocount foopriority joober
 * plugh.3 plugh.47 plugh.8 zot
 */
```

Doing a little debugging, the `jsdocParser` option is never included in the `options` dictionary in the `maybeOptions` [passed into getParser](https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/33afeb7f9605f061647abf617a6ded4d14ae1bc2/src/parser.ts#L31). I suppose Prettier omits options that aren't reported.

Would you be willing to add a global option for to enable the plugin that defaults to true?

**Comment by hosseinmd** [comment]
Fixed v0.3.34

**Comment by DaniGuardiola** [comment]
This is still happening to me in v0.4.2 (can't upgrade yet because of Prettier <v3)

**Comment by hosseinmd** [comment]
```
{
"prettier": "^3.0.0",
"prettier-plugin-jsdoc":"^1.0.1"
}
```
I tested with this config, but I didn't face with problem again.
